### ISSUE TITLE
A way to get the branch name and the commit hash

### ISSUE THREAD

**Issue by darhal** [Sniddl/discord-commits#13]
I wonder if there is a way to access the branch name and the commit hash using the `github.context.payload`. 
I digged into the github payload [documentations ](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#push) and couldn't find anything useful to what I'm trying to do .
I would be thankful if anyone can help me with this.

**Comment by ZebTheWizard** [comment]
It looks like `github.sha` will give you the hash, and the branch name can be parsed out of the `github.ref`
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
