### ISSUE TITLE
Can you ommit the message?

### ISSUE THREAD

**Issue by Andre601** [Sniddl/discord-commits#2]
I want to use this GitHub action to send notifications when a page has been deployed.
But I don't need the message part of the action, since I only want to send the embed object itse.

Can I just leave away the message object, or provide an empty String as content for it to work?

**Comment by ZebTheWizard** [comment]
It looks like it should work.

**Comment by ZebTheWizard** [comment]
You can completely omit the message line. You don't have to use an empty string. I just made an examples folder that includes this issue. https://github.com/Sniddl/discord-commits/blob/master/examples/no_message.yml
