### ISSUE TITLE
Suggestion: Add option to alter webhook name and avatar used.

### ISSUE THREAD

**Issue by Andre601** [Sniddl/discord-commits#3]
It would be quite awesome if this action could receive options to alter the name and avatar of the webhook.

**Comment by ZebTheWizard** [comment]
I will look into this. On my projects I just change the avatar and name using the webhook settings.

Are you looking for something dynamic?

**Comment by Andre601** [comment]
Not really, but I think many people would appreciate having such an option.

**Comment by ZebTheWizard** [comment]
Should be possible in `>=v1.5`.  For example, you can customize the `embed.author.icon_url` 

https://github.com/Sniddl/discord-commits/blob/v1.6/discord-commits/templates/avatar-with-link.mjs
